include(FeatureSummary)
include(CMakePackageConfigHelpers)

list(APPEND INSTALL_TARGETS ${LIB_NAME_MAIN})
if (bip3x_BUILD_JNI_BINDINGS)
#	list(APPEND INSTALL_TARGETS ${LIB_NAME_JNI})
install(
	TARGETS ${LIB_NAME_JNI}
	EXPORT ${PROJECT_NAME}-targets
	RUNTIME DESTINATION ${INSTALL_BIN_DIR}
	LIBRARY DESTINATION ${INSTALL_LIB_DIR}
	ARCHIVE DESTINATION ${INSTALL_LIB_DIR}
)
endif ()
if (bip3x_BUILD_C_BINDINGS)
	list(APPEND INSTALL_TARGETS ${LIB_NAME_C})
endif ()
set(INSTALL_BIN_DIR bin)
set(INSTALL_LIB_DIR lib)
set(INSTALL_CMAKE_DIR ${INSTALL_LIB_DIR}/cmake)
set(INSTALL_INCLUDE_DIR include)

configure_package_config_file(
	${CMAKE_CURRENT_SOURCE_DIR}/cfg/${PROJECT_NAME}-config.cmake.in
	${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config.cmake
	INSTALL_DESTINATION ${INSTALL_CMAKE_DIR}
	PATH_VARS INSTALL_LIB_DIR INSTALL_INCLUDE_DIR INSTALL_CMAKE_DIR
)

write_basic_package_version_file(
	${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config-version.cmake
	VERSION ${PROJECT_VERSION}
	COMPATIBILITY SameMajorVersion)

list(JOIN INSTALL_TARGETS " -l" INSTALL_TARGETS_LINK_FLAG)
set(INSTALL_TARGETS_LINK_FLAG "-l${INSTALL_TARGETS_LINK_FLAG}")


# PKGCONFIG
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cfg/${PROJECT_NAME}.pc.in ${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/${PROJECT_NAME}.pc @ONLY)
if (bip3x_BUILD_JNI_BINDINGS)
	configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cfg/${PROJECT_NAME}_jni.pc.in ${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/${PROJECT_NAME}_jni.pc @ONLY)
	install(
		FILES
		${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/${PROJECT_NAME}_jni.pc
		DESTINATION lib/pkgconfig
	)
endif ()
if (bip3x_BUILD_C_BINDINGS)
	configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cfg/c${PROJECT_NAME}.pc.in ${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/c${PROJECT_NAME}.pc @ONLY)
	install(
		DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/c${PROJECT_NAME}
		DESTINATION ${INSTALL_INCLUDE_DIR}
	)
	install(
		FILES
		${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/c${PROJECT_NAME}.pc
		DESTINATION lib/pkgconfig
	)
endif ()


install(FILES
        ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config.cmake
        ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config-version.cmake
        DESTINATION ${INSTALL_CMAKE_DIR}
        )

if (NOT CMAKE_CONAN_BUILD)
	install(
		DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/_deps/toolbox-src/include/toolbox
		DESTINATION ${INSTALL_INCLUDE_DIR}
	)
endif ()

install(
	DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/bip3x
	DESTINATION ${INSTALL_INCLUDE_DIR}
)
install(
	FILES
	${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/${PROJECT_NAME}.pc
	DESTINATION lib/pkgconfig
)

install(EXPORT ${PROJECT_NAME}-targets
        NAMESPACE ${PROJECT_NAME}::
        FILE "${PROJECT_NAME}-targets.cmake"
        DESTINATION ${INSTALL_CMAKE_DIR}
        )


install(
	TARGETS ${INSTALL_TARGETS}
	EXPORT ${PROJECT_NAME}-targets
	RUNTIME DESTINATION ${INSTALL_BIN_DIR}
	LIBRARY DESTINATION ${INSTALL_LIB_DIR}
	ARCHIVE DESTINATION ${INSTALL_LIB_DIR}
	PUBLIC_HEADER DESTINATION ${INSTALL_INCLUDE_DIR}
)


set(PACKAGE_RELEASE 0)
set(CPACK_PACKAGE_NAME bip3x)
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_VENDOR "Eduard Maximovich")
set(CPACK_PACKAGE_CONTACT "edward.vstock@gmail.com")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/edwardstock/bip3x")
set(CPACK_PACKAGE_VCS_URL "https://github.com/edwardstock/bip3x.git")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PROJECT_DESCRIPTION})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")

set(PACKAGE_EXT ".sh")
set(CPACK_GENERATOR "STGZ")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CMAKE_PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(UPLOAD_FILE_NAME ${CPACK_PACKAGE_FILE_NAME}.sh)

include(CPack)
