/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edwardstock_bip3x_NativeBip39 */

#ifndef _Included_com_edwardstock_bip3x_NativeBip39
#define _Included_com_edwardstock_bip3x_NativeBip39
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edwardstock_bip3x_NativeBip39
 * Method:    getLanguages
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_edwardstock_bip3x_NativeBip39_bip39GetLanguages(JNIEnv*, jclass);

JNIEXPORT jobjectArray JNICALL
Java_com_edwardstock_bip3x_NativeBip39_bip39GetWordsFromLanguage(
    JNIEnv* env, jclass type, jstring language_);

JNIEXPORT jobject JNICALL
Java_com_edwardstock_bip3x_NativeBip39_bip39EncodeBytes(
    JNIEnv* env, jclass type, jobject input, jstring language_, jint entropy);

JNIEXPORT jboolean JNICALL
Java_com_edwardstock_bip3x_NativeBip39_bip39ValidateMnemonic(
    JNIEnv* env, jclass, jstring mnemonic_, jstring language_);

JNIEXPORT jbyteArray JNICALL
Java_com_edwardstock_bip3x_NativeBip39_bip39WordsToSeed(
    JNIEnv* env, jclass type, jstring mnemonic_);

JNIEXPORT jobject JNICALL
Java_com_edwardstock_bip3x_NativeBip39_bip39Generate(
    JNIEnv* env, jclass type, jstring language_, jint entropy);

#ifdef __cplusplus
}

#endif
#endif
