/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_minter_mintercore_bip39_NativeBip39 */

#ifndef _Included_network_minter_mintercore_bip39_NativeBip39
#define _Included_network_minter_mintercore_bip39_NativeBip39
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     network_minter_mintercore_bip39_NativeBip39
 * Method:    getLanguages
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_network_minter_mintercore_bip39_NativeBip39_getLanguages
  (JNIEnv *, jclass);

#ifdef __cplusplus
}

#endif
#endif
