name: Run Tests

on:
  pull_request:

jobs:
  build-and-test-with-conan:
    name: Build and Test with Conan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Setup Conan
        uses: ./.github/actions/setup-conan
        with:
          artifactory_api_key: ${{ secrets.ARTIFACTORY_API_KEY }}

      - name: Run Tests
        uses: ./.github/actions/run-tests
        with:
          cmake-args: "-Dbip3x_BUILD_TESTS=On -Dbip3x_BUILD_JNI_BINDINGS=On -Dbip3x_BUILD_C_BINDINGS=On"
          conan-enabled: true

  build-and-test-without-conan:
    name: Build and Test without Conan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Run Tests
        uses: ./.github/actions/run-tests
        with:
          cmake-args: "-Dbip3x_BUILD_TESTS=On -Dbip3x_BUILD_JNI_BINDINGS=On -Dbip3x_BUILD_C_BINDINGS=On"
          conan-enabled: false

      - name: Build target
        uses: ./.github/actions/build-cmake-target
        with:
          target: all
